### ISSUE TITLE
Documentation does not render lists inside of [info] tags correctly

### ISSUE THREAD

**Issue by cotpat** [silverstripe/doc.silverstripe.org#280] opened 2023-11-28 09:16 UTC
Lists seem to break detection of at least the closing `[/info]` tag. This may or may not be related to the lack of a newline after the last list item. Due to the closing tag not being detected correctly, subsequent tags (such as `[notice]`) will not render correctly either. This persists until the next `[/info]` tag is encountered.

The issue is visible e.g. on the [doc page for templating](https://docs.silverstripe.org/en/5/developer_guides/templates/syntax/#variables), just underneath the linked header (starting with the `Foo` example list).

Source code for that, in case that page gets updated:

```md
[info]
Arguments passed into methods can be any non-array literal type (not just strings), e.g:

- `$Foo(1)` will pass `1` as an int
- `$Foo(0.5)` will pass `0.5` as a float
- `$Foo(true)` will pass `true` as a boolean
- `$Foo(null)` will pass `null` as a null primitive
- `$Foo("param")`, `$Foo('param')`, and `$Foo(param)` will all pass `'param'` as a string. It is recommended that you always use quotes when passing a string for clarity
[/info]
```

**Comment by GuySartorelli** [comment] 2023-11-30 21:35
This happens because the `[/info]` closing tag is technically _inside_ the list, so the regex in https://github.com/silverstripe/doc.silverstripe.org/blob/master/src/utils/cleanCalloutTags.ts doesn't capture it correctly.

We might have to start doing something a little more sophisticated here. https://github.com/silverstripe/developer-docs/issues/388 has some suggestions we might want to look into.

We could alternatively just implement https://github.com/silverstripe/developer-docs/issues/388 and have part of the linting rules be that there's an empty linebreak before the closing tag - in that case we wouldn't need to fix the actual bug.

**Comment by emteknetnz** [comment] 2024-01-07 21:08
Duplicate of https://github.com/silverstripe/developer-docs/issues/431

**Closed by emteknetnz** 2024-01-07 21:08 UTC
Labels: type/bug
