### ISSUE TITLE
Reversed children sometimes aren't reversed

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/doc.silverstripe.org#210] opened 2019-11-20 22:56 UTC
Rendered children seem to have several different states fighting with each other.
Here's an example of `[CHILDREN reverse]`.

(Click on the menu item seems to be triggering the state change).
![peek-docs-20191121](https://user-images.githubusercontent.com/9313746/69285444-cd0a9e00-0c55-11ea-983a-14353d933974.gif)

**Comment by stevie-mayhew** [comment] 2019-11-20 23:23
Perhaps this is a feature, not a bug.

**Comment by unclecheese** [comment] 2020-02-28 02:52
Fixed by https://github.com/silverstripe/doc.silverstripe.org/commit/b0b8947e7473043dc99673dc78aa9d0d9793e1f8

**Closed by unclecheese** 2020-02-28 02:52 UTC
